### PR TITLE
Add build configuration for lgtm.com

### PR DESCRIPTION
**Pull request by aibaars**
This pull request adds an `.lgtm.yml` configuration file to teach lgtm.com to build this repository.

See also: https://discuss.lgtm.com/t/cannot-build-ant-build-logs-unhelpful/736/2
@paradoxengine

### CODE REVIEW

**Comment by aibaars** [comment]
I signed

**Comment by paradoxengine** [comment]
Thank you!

**Comment by sirdarckcat** [comment]
@aibaars do you know why https://lgtm.com/projects/g/google/firing-range/latest/files/src/?sort=name&dir=ASC&mode=heatmap&excluded=false doesn't show https://github.com/google/firing-range/tree/master/src/pages

**Comment by aibaars** [comment]
@sirdarckcat lgtm.com currently analyses java, javascript, python, and c/c++ code. The `src/pages` folder contains mostly html code, which we do analyse as part of the javascript analysis. Unfortunately, lgtm considered the amount of javascript files (0.1% according to github) to be too small. Let me see if I can enable javascript analysis for your repository, so it will analyse the javascript in the html pages.

**Comment by sirdarckcat** [comment]
@aibaars it also didn't index the Java files it seems

https://github.com/google/firing-range/blob/master/src/tests/escape/JsEscape.java

**Comment by sirdarckcat** [comment]
(this shows empty: https://lgtm.com/projects/g/google/firing-range/latest/files/src/tests/escape/?sort=name&dir=ASC&mode=heatmap&excluded=false )

**Comment by aibaars** [comment]
We filter out test code, generated code, and some more things by default, but you can unhide them with the funny button on the left. https://lgtm.com/projects/g/google/firing-range/latest/files/src/tests/escape/?sort=name&dir=ASC&mode=heatmap&excluded=true

**Comment by sirdarckcat** [comment]
thanks :) that worked.

**Pull request merged**
